WITH MONTHLYSALES AS (
    SELECT
        CAST(FORMAT(SALEDATE, 'YYYY-MM-01') AS DATE) AS SALEMONTH,
        REGION,
        PRODUCTID,
        SUM(SALEAMOUNT) AS TOTALSALES
    FROM SALESDATA
    GROUP BY 1, 2, 3
),

RANKEDPRODUCTS AS (
    SELECT
        SALEMONTH,
        REGION,
        PRODUCTID,
        TOTALSALES,
        RANK()
            OVER (PARTITION BY SALEMONTH, REGION ORDER BY TOTALSALES DESC)
            AS PRODUCTRANK
    FROM MONTHLYSALES
),

PREVIOUSMONTHSALES AS (
    SELECT
        SALEMONTH,
        REGION,
        PRODUCTID,
        TOTALSALES AS CURRENTMONTHSALES,
        LAG(TOTALSALES, 1, 0)
            OVER (PARTITION BY REGION, PRODUCTID ORDER BY SALEMONTH)
            AS PREVIOUSMONTHSALES
    FROM MONTHLYSALES
)

SELECT
    RP.SALEMONTH,
    RP.REGION,
    RP.PRODUCTID,
    RP.TOTALSALES,
    RP.PRODUCTRANK,
    (PMS.CURRENTMONTHSALES - PMS.PREVIOUSMONTHSALES)
        AS SALESDIFFERENCEFROMPREVIOUSMONTH
FROM RANKEDPRODUCTS AS RP
INNER JOIN PREVIOUSMONTHSALES AS PMS
    ON
        RP.SALEMONTH = PMS.SALEMONTH
        AND RP.REGION = PMS.REGION
        AND RP.PRODUCTID = PMS.PRODUCTID
WHERE RP.PRODUCTRANK <= 5
ORDER BY RP.SALEMONTH DESC, RP.REGION ASC, RP.PRODUCTRANK ASC;
