name: Lint SQL
on:
  - push
jobs:
  sqlfluff: null
  runs-on: ubuntu-latest
  steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.x"
    - name: Install SQLFluff
      run: pip install sqlfluff
    - name: Run SQLFluff
      run: sqlfluff lint src/sql/
