on: [push]

jobs:
  reformat-sql:
    runs-on: ubuntu-latest
    steps:
      # Checkout the source code there are have some files to look at.
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          token: ${{secrets.SOURCE_PUSH_TOKEN}}
          
      # Run the reformat action
      - name: Reformat SQL Files
        uses: credfeto/action-sql-format@v1.5.1
        
      # Commit any changes to the repo
      - uses: stefanzweifel/git-auto-commit-action@v5.0.0
        with:
          commit_message: "[Reformat] SQL Files to common format"
          file_pattern: "*.sql"
          commit_user_name: "sqlfmt[bot]"
          commit_user_email: "github-username@users.noreply.github.com"
          commit_author: "sqlfmt[bot] <github-username@users.noreply.github.com>"
          skip_dirty_check: false
