name: Static Code Analysis

on:  # yamllint disable-line rule:truthy
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10.11'

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/pip
          ~/.cache/pip-tools
          ~/.cache/pre-commit
        key: $-pip-$
        restore-keys: |
          $-pip-

    - id: file_changes
      uses: tj-actions/changed-files@v44

    - name: Install all Python dependencies.
      env:
        PYTHON_SRC_DIR: CICD
      run: |
        python -m pip install -U pip
        python -m pip install pip-tools
        pip-compile ${PYTHON_SRC_DIR}/requirements.in --output-file ${PYTHON_SRC_DIR}/requirements.out
        python -m pip install -r ${PYTHON_SRC_DIR}/requirements.out

    - name: Run the pre-commit.
      env:
        ALL_CHANGED_FILES: $
        SKIP: no-commit-to-branch
      run: |
        set -e  # Exit with code 1, if a command fails
        echo ${ALL_CHANGED_FILES}
        if [ -n "${ALL_CHANGED_FILES}" ]; then
          echo "Running pre-commit on the following files: ${ALL_CHANGED_FILES}"
          pre-commit run --show-diff-on-failure --files ${ALL_CHANGED_FILES}
        else
          echo "No changed files to run pre-commit on."
        fi

    - name: Check for changes in Python files and commit them.
      id: check_python_changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

        # Check for modified Python files after running pre-commit
        MODIFIED_PYTHON_FILES=$(git ls-files --modified | grep -E '\.py$' || echo '')

        if [ -n "$MODIFIED_PYTHON_FILES" ]; then
          echo "Changes detected in the following Python files:"
          echo "${MODIFIED_PYTHON_FILES}"

          git add "${MODIFIED_PYTHON_FILES}"
          git commit -m "Auto-format: Applied black and isort formatting to Python files"
          git push origin $
        fi
